# Generated by Django 3.1.3 on 2023-04-29 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_auto_20230330_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfs',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 30)),
        ),
        migrations.AddField(
            model_name='turfs',
            name='time',
            field=models.CharField(default=datetime.time(6, 0), max_length=200),
        ),
    ]
