# Generated by Django 3.1.3 on 2023-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_auto_20230429_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfs',
            name='booked',
            field=models.IntegerField(default=0),
        ),
    ]
